const ProductsData = [
  {
    id: "1",
    name: "L2A1 Multipurpose Car AC Vent Interior Dust Cleaning Gel Jelly",
    description:
      "Detaling Putty Cleaner for Car Interior, Keyboard, PC, Laptop",
    price: 161,
    rating: 4.3,
    category: "accessories",
    brand: "L2A1",
    imageUrl: "https://m.media-amazon.com/images/I/61+w9Ggew7L._AC_UL320_.jpg",
  },
  {
    id: "2",
    name: "Godrej aer O - Hanging Car Air Freshener",
    description: "Assorted Pack of 3, Lasts up to 30 days",
    price: 249,
    rating: 4.2,
    category: "accessories",
    brand: "Godrej",
    imageUrl: "https://m.media-amazon.com/images/I/6126Ihs3N4L._AC_UL320_.jpg",
  },
  {
    id: "3",
    name: "INOLVE Elements Aqua Spray Air Perfume",
    description: "Fine Fragrance Car Scent Air Freshener",
    price: 369,
    rating: 4.5,
    category: "accessories",
    brand: "INOLVE",
    imageUrl: "https://m.media-amazon.com/images/I/51Fx36mY1UL._AC_UL320_.jpg",
  },
  {
    id: "4",
    name: "HSR Car Accessories Car Sun Visor Organizer",
    description: "Sunglasses Pen Card Small Document Storage Pouch Holder",
    price: 346,
    rating: 4.6,
    category: "accessories",
    brand: "HSR",
    imageUrl: "https://m.media-amazon.com/images/I/717pZ1SKJdL._AC_UL320_.jpg",
  },
  {
    id: "5",
    name: "Adroitz Universal Car Neck Rest Cushion",
    description:
      "Durable Memory Foam, Ergonomic Headrest Support, Breathable Neck Relief",
    price: 179,
    rating: 4.4,
    category: "accessories",
    brand: "Adroitz",
    imageUrl: "https://m.media-amazon.com/images/I/81u4v3oILSL._AC_UL320_.jpg",
  },
  {
    id: "6",
    name: "Motomax 2K Rubbing Compound 200g",
    description:
      "Removes Minor Scratches, Swirl Marks, Paint Defects and Oxidation from Metal Surfaces",
    price: 157,
    rating: 4.7,
    category: "accessories",
    brand: "Motomax",
    imageUrl: "https://m.media-amazon.com/images/I/61unbiwjgvL._AC_UL320_.jpg",
  },
  {
    id: "7",
    name: "KRESHU Cordless 48V Electric High Pressure Car Washer Machine",
    description: "Portable Power ABS Material Multi-Function 3 in 1 Nozzle",
    price: 1999,
    rating: 4.3,
    category: "accessories",
    brand: "KRESHU",
    imageUrl: "https://m.media-amazon.com/images/I/614iRCIk6qL._AC_UL320_.jpg",
  },
  {
    id: "8",
    name: "SOLDFLY Car Door Edge Guards U Shape Edge Trim Rubber Seal",
    description: "Protector Rubber Clips Fit Car Doors",
    price: 309,
    rating: 4.2,
    category: "accessories",
    brand: "SOLDFLY",
    imageUrl: "https://m.media-amazon.com/images/I/51ZE3KKjGvL._AC_UL320_.jpg",
  },
  {
    id: "9",
    name: "PROTEGO All Weather Protection Car Cover for BMW 8 Series",
    description:
      "Anti Dust, 100% Waterproof, Multi-Layered, Electric Grip, Buckle Hook with Mirror Pockets",
    price: 2799,
    rating: 4.6,
    category: "accessories",
    brand: "PROTEGO",
    imageUrl: "https://m.media-amazon.com/images/I/51J9RtnRKzL._AC_UL320_.jpg",
  },
  {
    id: "10",
    name: "Cectics Tyre Inflator for Car - Smart Cordless Portable Air Compressor Pump",
    description: "Air Inflator for Car, Bike, Bicycle, Balls, Rechargeable",
    price: 2499,
    rating: 4.4,
    category: "accessories",
    brand: "Cectics",
    imageUrl: "https://m.media-amazon.com/images/I/610uZPznH3L._AC_UL320_.jpg",
  },
  {
    id: "11",
    name: "Mouse H",
    description: "Wireless ergonomic mouse",
    price: 44.99,
    rating: 4.1,
    category: "accessories",
    brand: "ClickEase",
    stock: 60,
    imageUrl: "https://example.com/images/mouse-h.jpg",
  },
  {
    id: "12",
    name: "Speaker I",
    description: "Bluetooth speaker with deep bass",
    price: 69.99,
    rating: 4.5,
    category: "accessories",
    brand: "BassBoom",
    stock: 35,
    imageUrl: "https://example.com/images/speaker-i.jpg",
  },
  {
    id: "13",
    name: "Router J",
    description: "High-speed WiFi router",
    price: 139.99,
    rating: 4.4,
    category: "electronics",
    brand: "NetPower",
    stock: 25,
    imageUrl: "https://example.com/images/router-j.jpg",
  },
  {
    id: "14",
    name: "Drone K",
    description: "Compact drone with HD camera",
    price: 519.99,
    rating: 4.7,
    category: "electronics",
    brand: "SkyFly",
    stock: 10,
    imageUrl: "https://example.com/images/drone-k.jpg",
  },
  {
    id: "15",
    name: "Smart Light L",
    description: "Smart light bulb with app control",
    price: 29.99,
    rating: 4.2,
    category: "home",
    brand: "BrightHome",
    stock: 75,
    imageUrl: "https://example.com/images/smart-light-l.jpg",
  },
  {
    id: "16",
    name: "Scotch-Brite 2-in-1 Bucket Spin Mop (Green, 2 Refills), 4 Pcs",
    description: "Smart light bulb with app control",
    price: 29.99,
    rating: 4.2,
    category: "home",
    brand: "Scotch-Brite",
    stock: 75,
    imageUrl: "https://m.media-amazon.com/images/I/61ITlnte9uL._AC_UL320_.jpg",
  },
  {
    id: "17",
    name: "Conserva 16 LG Portable Aluminium Folding Trolley",
    description: "Portable and durable trolley for easy transportation",
    price: 3699,
    rating: 4.0,
    category: "home",
    brand: "Conserva",
    imageUrl: "https://m.media-amazon.com/images/I/5187K3eaGqL._AC_UL320_.jpg",
  },
  {
    id: "18",
    name: "Cosmetic Automatic Water Dispenser",
    description: "Automatic water dispenser for skincare and beauty routines",
    price: 799,
    rating: 4.3,
    category: "home",
    brand: "Cosmetic",
    imageUrl: "https://m.media-amazon.com/images/I/61mcImxZy1L._AC_UL320_.jpg",
  },
  {
    id: "19",
    name: "Temno 16 Light Bulb Wireless Wi-Fi Control",
    description: "Smart light bulb with wireless control via app",
    price: 1299,
    rating: 4.5,
    category: "home",
    brand: "Temno",
    imageUrl: "https://m.media-amazon.com/images/I/512A0ubnpWL._AC_UL320_.jpg",
  },
  {
    id: "20",
    name: "Bodyfit Adjustable Hand Grip Strengthener",
    description: "Adjustable hand grip strengthener for home fitness",
    price: 1864,
    rating: 4.6,
    category: "home",
    brand: "Bodyfit",
    imageUrl: "https://m.media-amazon.com/images/I/61Av1lptLkL._AC_UL320_.jpg",
  },
  {
    id: "21",
    name: "Havells LED Bulb Set",
    description: "Energy-efficient LED bulbs for home lighting",
    price: 59,
    rating: 4.1,
    category: "home",
    brand: "Havells",
    imageUrl: "https://m.media-amazon.com/images/I/61FdvLeUYtL._AC_UL320_.jpg",
  },
  {
    id: "23",
    name: "Chilly Lights 3 LED Panel Lights",
    description: "Set of 3 LED panel lights with energy-saving features",
    price: 1299,
    rating: 4.4,
    category: "home",
    brand: "Chilly Lights",
    imageUrl: "https://m.media-amazon.com/images/I/71J611GkcYL._AC_UL320_.jpg",
  },
  {
    id: "24",
    name: "iBabySmart Air Roller for Air Purification",
    description: "Portable air purifier for improved air quality at home",
    price: 1999,
    rating: 4.6,
    category: "home",
    brand: "iBabySmart",
    imageUrl: "https://m.media-amazon.com/images/I/71Vt2Pgy4hL._AC_UL320_.jpg",
  },
  {
    id: "25",
    name: "Panasonic Wireless Adapter",
    description: "Wireless adapter for easy home connectivity",
    price: 698,
    rating: 4.2,
    category: "home",
    brand: "Panasonic",
    imageUrl: "https://m.media-amazon.com/images/I/51XGcwwG8qL._AC_UL320_.jpg",
  },
  {
    id: "26",
    name: "AllExtreme CYL-06-T Multi-Purpose Bike Chain Cleaner Brush",
    description: "Soft and long bristles for quick and easy cleaning of bike chains.",
    price: 149,
    rating: 4.5,
    category: "bike accessories",
    brand: "AllExtreme",
    imageUrl: "https://m.media-amazon.com/images/I/610XWnl+nXL._AC_UL320_.jpg"
  },
  {
    id: "27",
    name: "Autofy Universal Bike Cover",
    description: "UV protection and dustproof bike body cover for two-wheelers.",
    price: 248,
    rating: 4.2,
    category: "bike accessories",
    brand: "Autofy",
    imageUrl: "https://m.media-amazon.com/images/I/51k9wNfghBS._AC_UL320_.jpg"
  },
  {
    id: "28",
    name: "OTO2EYE Aluminium Airplane Light (7 Colors)",
    description: "Waterproof universal warning signal blinker LED.",
    price: 99,
    rating: 4.0,
    category: "bike accessories",
    brand: "OTO2EYE",
    imageUrl: "https://m.media-amazon.com/images/I/61jT-ysEfnL._AC_UL320_.jpg"
  },
  {
    id: "29",
    name: "Motomax Bike Liquid Polish",
    description: "Removes tough stains, provides high gloss and shine on painted surfaces.",
    price: 33,
    rating: 4.3,
    category: "bike accessories",
    brand: "Motomax",
    imageUrl: "https://m.media-amazon.com/images/I/51Wi9-kFOxL._AC_UL320_.jpg"
  },
  {
    id: "30",
    name: "Kandid Advance Heavy Duty Digital Number Lock",
    description: "Universal combination cable lock for bike and helmet security.",
    price: 199,
    rating: 4.2,
    category: "bike accessories",
    brand: "Kandid",
    imageUrl: "https://m.media-amazon.com/images/I/61z0Kx1ifGL._AC_UL320_.jpg"
  },
  {
    id: "31",
    name: "RADIANT Car Dustbin",
    description: "Mini car trash bin for maintaining cleanliness inside your car.",
    price: 149,
    rating: 4.4,
    category: "car accessories",
    brand: "RADIANT",
    imageUrl: "https://m.media-amazon.com/images/I/51BLWSTs7NL._AC_UL320_.jpg"
  },
  {
    id: "32",
    name: "SOFTSPUN Microfiber Cloth - 4 pcs",
    description: "Thick lint and streak-free multipurpose microfiber cloths (340 GSM).",
    price: 299,
    rating: 4.7,
    category: "car accessories",
    brand: "SOFTSPUN",
    imageUrl: "https://m.media-amazon.com/images/I/81dsWgzXLrL._AC_UL320_.jpg"
  },
  {
    id: "33",
    name: "Automaze Center Console Armrest Cover Pad",
    description: "Comfortable armrest cover pad with side pockets, universal fit for SUVs.",
    price: 807,
    rating: 4.2,
    category: "car accessories",
    brand: "Automaze",
    imageUrl: "https://m.media-amazon.com/images/I/61azD0IlH7L._AC_UL320_.jpg"
  },
  {
    id: "34",
    name: "CAR BASICS French Vanilla Wood Perfume",
    description: "Solid wood perfume with two free dropper bottles of fragrance oil.",
    price: 369,
    rating: 3.8,
    category: "car accessories",
    brand: "CAR BASICS",
    imageUrl: "https://m.media-amazon.com/images/I/71zeJqcae5L._AC_UL320_.jpg"
  },
  {
    id: "35",
    name: "ADINOX 100% Waterproof Jungle Print Car Cover",
    description: "Heavy-duty fabric car cover compatible with Maruti Suzuki Alto K10.",
    price: 1840,
    rating: 4.5,
    category: "car accessories",
    brand: "ADINOX",
    imageUrl: "https://m.media-amazon.com/images/I/61nGOS2QFwL._AC_UL320_.jpg"
  }
];

export default ProductsData;
